from sparse_categorical_crossentropy import SPARSE_CATEGORICAL_CROSS_ENTROPY
from binary_crossentropy import BINARY_CROSS_ENTROPY
from categorical_crossentropy import CATEGORICAL_CROSS_ENTROPY
from MSE import MSE
from MAE import MAE